### ISSUE TITLE
Regression of Blank screen on simulator sdk #46

### ISSUE THREAD

**Issue by steelzeh** [ionic-team/ionic-portals-ios#76] opened 2023-06-29 10:32 UTC
Regression of this issue? https://github.com/ionic-team/ionic-portals-ios/issues/46

Seems that this issue is back with the latest version of IonicPortals.
Console log in xcode says: ⚡️  Loading app at capacitor://localhost but blank screen in Simulator, on local device it works fine.

**Comment by Steven0351** [comment] 2023-06-29 15:17
Can you please provide a minimal repro, along with the version of Portals and Capacitor that are in your project?

**Comment by steelzeh** [comment] 2023-07-04 12:52
[portals-test.zip](https://github.com/ionic-team/ionic-portals-ios/files/11949187/portals-test.zip)
Sorry for the late answer, didn't get an email or notification.
Remember to update the Token for it to run.

I am using Xcode 14.2, macOS Ventura 13.4, running on iPad Air (5th generation) simulator (iOS 16.2)

Also in the lastest version of Capacitor 5.1, there seems to be an infinite loop loading the webview and capactiorBridge, because they both are lazily loading assetHandler, which tries to load the capacitorBridge, which tries to load the assetHandler and so on and so on and so on

**Comment by Steven0351** [comment] 2023-07-04 17:39
Yeah you should downgrade to anything below 5.1. I patched the issue when I discovered it on Monday but a release hasn’t been cut for it yet.

**Comment by steelzeh** [comment] 2023-07-04 18:40
Yeah, but 5.0 still doesnt work, blank white screen on simulator

**Comment by Steven0351** [comment] 2023-07-04 19:44
Personally, the problem is highly likely with capacitor and this issue likely belongs over there. Today is a holiday in the US so no one is actually going to be looking into this until later this week.

**Comment by Steven0351** [comment] 2023-07-05 14:50
I ran this both with a patched 5.1 (that fixes the lazy init) and with 5.0.5. Unable to reproduce. ![simulator_screenshot_5133AC86-1DF8-4445-88ED-EB28E666CA3A](https://github.com/ionic-team/ionic-portals-ios/assets/24440751/082dc312-e6bb-4c30-bfd5-576192cc2988)

**Comment by steelzeh** [comment] 2023-07-06 08:46
Alright i will give it a go

**Comment by Steven0351** [comment] 2023-07-11 15:09
Hopefully this was resolved by upgrading Xcode. If it wasn't, this would specifically be a Capacitor issue and should be raised over there. There isn't anything I can do from the Portals side to fix this issue for you.

**Closed by Steven0351** 2023-07-11 15:09 UTC
